<p align="center">
  <img src="images/picture.png" alt="Michael Teixeira's Logo" />
</p>

<p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/michael-teixeira-66298024a/">LinkedIn</a> |
  <a href="https://github.com/Tex30">GitHub</a>
</p>

<p align="justify">
  Pursuing Graduate Certificate in Data Science at RMIT.
</p>
