title: Michael Teixeira
description: |
  <div align="center">
    <img src="/images/picture.png?raw=true" alt="Michael Teixeira" style="max-width: 200px; border-radius: 50%; margin-bottom: 15px;">
    
    <p>
    <a href="pdf/resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/michael-teixeira-66298024a/">LinkedIn</a> |
    <a href="https://github.com/Tex30">GitHub</a>
    </p>
    
    <p>
    I am pursuing Graduate Certificate in Data Science at RMIT.
    </p>
  </div>
  
theme: jekyll-theme-minimal
google_analytics: G-6MB61WNNMV
