title:  Michael Teixeira

logo: "/images/picture.png?raw=true"

description:
  <p align="left">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/michael-teixeira-66298024a/">LinkedIn</a> |
  <a href="https://github.com/Tex30">GitHub</a>
  </p>
  
  <p align="justify">
  Data Science Graduate Student | Data Analytics Professional | Python, R & SQL | Machine Learning Enthusiast
    </p>
  
theme: jekyll-theme-minimal
google_analytics: G-6MB61WNNMV # Google Analytics tracking ID
